
os: linux
dist: focal

vm:
  size: 2x-large

language: go
go:
- 1.18.x

addons:
  apt:
    packages:
    - rpm
go_import_path: github.com/nats-io/nats-server

jobs:
  include:
    - name: "Compile and various other checks"
      env: TEST_SUITE=compile
    - name: "Run TestNoRace tests"
      env: TEST_SUITE=no_race_tests
    - name: "Run JetStream tests"
      env: TEST_SUITE=js_tests
    - name: "Run JetStream cluster tests"
      env: TEST_SUITE=js_cluster_tests
    - name: "Run JetStream super cluster tests"
      env: TEST_SUITE=js_super_cluster_tests
    - name: "Run non JetStream tests from the server package"
      env: TEST_SUITE=srv_pkg_non_js_tests
    - name: "Run all tests from all other packages"
      env: TEST_SUITE=non_srv_pkg_tests
    - name: "Compile with older Go release"
      go: 1.17.x
      env: TEST_SUITE=build_only

script: ./scripts/runTestsOnTravis.sh $TEST_SUITE

deploy:
  provider: script
  cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: ($TRAVIS_GO_VERSION =~ 1.18) && ($TEST_SUITE = "compile")
