
os: linux
dist: focal

vm:
  size: 2x-large

language: go
go:
- 1.17.x
- 1.16.x
addons:
  apt:
    packages:
    - rpm
env:
- GO111MODULE=off
go_import_path: github.com/nats-io/nats-server
install:
- GO111MODULE=on go install honnef.co/go/tools/cmd/staticcheck@latest
- GO111MODULE=on go install github.com/client9/misspell/cmd/misspell@latest
before_script:
- GO_LIST=$(go list ./...)
- go build
- $(exit $(go fmt $GO_LIST | wc -l))
- go vet $GO_LIST
- find . -type f -name "*.go" | grep -v "/vendor/" | xargs misspell -error -locale US
- staticcheck $GO_LIST
script:
- set -e
- if [[ $TRAVIS_TAG ]]; then go test -v -run=TestVersionMatchesTag ./server; fi
- if [[ ! $TRAVIS_TAG ]]; then go test -v -run=TestNoRace --failfast -p=1 -timeout 20m ./...; fi
- if [[ ! $TRAVIS_TAG ]]; then if [[ "$TRAVIS_GO_VERSION" =~ 1.16 ]]; then ./scripts/cov.sh TRAVIS; else go test -v -race -p=1 --failfast -timeout 20m ./...; fi; fi
- set +e
after_success:
- if [[ ! $TRAVIS_TAG ]]; then if [[ "$TRAVIS_GO_VERSION" =~ 1.16 ]]; then $HOME/gopath/bin/goveralls -coverprofile=acc.out -service travis-ci; fi; fi

deploy:
  provider: script
  cleanup: true
  script: curl -sL http://git.io/goreleaser | VERSION=v0.160.0 bash
  on:
    tags: true
    condition: $TRAVIS_GO_VERSION =~ 1.16
