name: MQTTEx
on: [push, pull_request]

jobs:
  test:
    env:
      GOPATH: /home/runner/work/nats-server
      GO111MODULE: "on"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: src/github.com/nats-io/nats-server

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: src/github.com/nats-io/nats-server/go.mod
          cache-dependency-path: src/github.com/nats-io/nats-server/go.sum

      - name: Set up testing tools and environment
        shell: bash --noprofile --norc -eo pipefail {0}
        id: setup
        run: |
          wget https://github.com/hivemq/mqtt-cli/releases/download/v4.20.0/mqtt-cli-4.20.0.deb
          sudo apt install ./mqtt-cli-4.20.0.deb
          go install github.com/ConnectEverything/mqtt-test@v0.1.0

      - name: Run tests and benchmarks
        shell: bash --noprofile --norc -eo pipefail {0}
        run: |
          cd src/github.com/nats-io/nats-server
          go test -v --run='MQTTEx' ./server
          go test -v --race --failfast --run='MQTTEx' ./server
          go test --run='-' --count=3 --bench 'MQTTEx' --benchtime=100x ./server

      # TODO: compare benchmarks
